name: "4.Service Request"
description: "Form to submit standard user support queries or minor requests."

assignees: ["keradin"]
labels: []
projects: ["A3W-HELOISA/Operations"]
title: "Service Request: <Short description of request>"
type: 4.Service Request

body:

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Explanation of what the user needs and why."
      placeholder: "Provide detailed information."

  - type: textarea
    id: fulfillment_notes
    attributes:
      label: "Fulfillment Notes"
      description: "Information on how the request was addressed or fulfilled."
      placeholder: "Provide fulfillment details."
