name: "Change Request"
description: "Form to submit a formal proposal for service, system, or process modifications."
assignees:
  - "" # Add default assignee here if applicable
labels:
  - "Ph.Change"
  - "S.2-Pending Approval"
projects:
  - "HELOISA Operations - Service Management"
title : "Change Request to xxx"
type: "it_Change Request"

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Detailed explanation of the proposed change, including rationale and objectives."
      placeholder: "Provide a detailed description of the change."
  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: "Specify the type of request."
      options:
        - "it_Change Request"
        - "it_Incident"
        - "it_Problem"
        - "it_Service Request"
  - type: textarea
    id: impact_analysis
    attributes:
      label: "Impact Analysis"
      description: "Describe how the change will affect existing systems or users."
      placeholder: "Provide an impact assessment."
  - type: textarea
    id: approval_details
    attributes:
      label: "Approval Details"
      description: "Provide status and notes from the Change Advisory Board or relevant stakeholders."
      placeholder: "Details of approvals or comments from stakeholders."
  - type: textarea
    id: implementation_plan
    attributes:
      label: "Implementation Plan"
      description: "List steps for implementation, testing, and rollback."
      placeholder: "Outline your implementation plan."
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Select the current status of the change request."
      options:
        - "2-Pending Approval"
        - "1-Open"
        - "3-Under Review"
        - "4-Completed"
    validations:
      required: true

