name: "Problem"
description: "Form to identify the root cause of recurring incidents or service disruptions."
assignees:
  - "" # Add default assignee here if applicable
labels:
  - "Ph.Problem"
  - "S.2-Pending Approval"
projects:
  - "HELOISA Operations - Service Management"
title : "A problem occured in xxx"
type: "it_Problem"

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "In-depth analysis of the problem, including related incidents."
      placeholder: "Provide a detailed description."
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select the importance level of the request."
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: textarea
    id: root_cause_analysis
    attributes:
      label: "Root Cause Analysis"
      description: "Identify the underlying cause(s) of the issue."
      placeholder: "Provide the root cause analysis."
  - type: textarea
    id: proposed_solutions
    attributes:
      label: "Proposed Solutions"
      description: "Suggestions to resolve the issue permanently."
      placeholder: "List possible solutions."
  - type: textarea
    id: resolution_plan
    attributes:
      label: "Resolution Plan"
      description: "Steps to implement the solutions, including testing and validation."
      placeholder: "Outline the resolution plan."
